let products = [
    {
        "id": 1001,
        "title": "Maths",
        "location": "London",
        "price": 99.99,
        "space": 5,
        "image": "img/calculator.png",
    },
    {
        "id": 1002,
        "title": "English",
        "location": "Birmingham",
        "price": 69.99,
        "space": 19,
        "image": "img/eng.png",
    },
    {
        "id": 1003,
        "title": "Chemistry",
        "location": "Manchester",
        "price": 79.99,
        "space": 16,
        "image": "img/chemistry.png",
    },
    {

        "id": 1004,
        "title": "Software Engineering",
        "location": "Cambridge",
        "price": 109.99,
        "space": 23,
        "image": "img/code.png",
    },
    {
        "id": 1005,
        "title": "History",
        "location": "Derby",
        "price": 49.99,
        "space": 56,
        "image": "img/history.png",
    },
    {
        "id": 1006,
        "title": "Arts",
        "location": "Nottingham",
        "price": 54.99,
        "space": 10,
        "image": "img/art.png",
    },
    {
        "id": 1007,
        "title": "Dance",
        "location": "Exeter",
        "price": 39.99,
        "space": 48,
        "image": "img/dance.png",
    },
    {
        "id": 1008,
        "title": "Martial Arts",
        "location": "Wolverhampton",
        "price": 19.99,
        "space": 8,
        "image": "img/ma.png",
    },
    {
        "id": 1009,
        "title": "Sports",
        "location": "Sheffield",
        "price": 44.99,
        "space": 80,
        "image": "img/sports.png",
    },
    {
        "id": 1010,
        "title": "Law",
        "location": "Oxford",
        "price": 119.99,
        "space": 20,
        "image": "img/law.png",
    }
]