let products = [
    {
        "id": 1001,
        "title": "Maths",
        "location": "London",
        "price": 99.99,
        "space": 10,
        "image": "",
    },
    {
        "id": 1002,
        "title": "English",
        "location": "London",
        "price": 69.99,
        "space": 10,
        "image": "",
    },
    {
        "id": 1003,
        "title": "Chemistry",
        "location": "London",
        "price": 79.99,
        "space": 10,
        "image": "",
    },
    {

        "id": 1004,
        "title": "Software Engineering",
        "location": "London",
        "price": 109.99,
        "space": 10,
        "image": "",
    },
    {
        "id": 1005,
        "title": "History",
        "location": "London",
        "price": 49.99,
        "space": 10,
        "image": "",
    },
    {
        "id": 1006,
        "title": "Arts",
        "location": "London",
        "price": 54.99,
        "space": 10,
        "image": "",
    },
    {
        "id": 1007,
        "title": "Dance",
        "location": "London",
        "price": 39.99,
        "space": 10,
        "image": "",
    },
    {
        "id": 1008,
        "title": "Martial Arts",
        "location": "London",
        "price": 19.99,
        "space": 10,
        "image": "",
    },
    {
        "id": 1009,
        "title": "Sports",
        "location": "London",
        "price": 44.99,
        "space": 10,
        "image": "",
    },
    {
        "id": 1010,
        "title": "Law",
        "location": "London",
        "price": 119.99,
        "space": 10,
        "image": "",
    }
]